// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hehe.proto
// Protobuf Java Version: 4.28.3

package IndProgramming2024Package.IndProgramming2024Project;

public final class Hehe {
  private Hehe() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Hehe.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExpressionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IndProgramming2024Package.IndProgramming2024Project.Expressions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string expression = 1;</code>
     * @return A list containing the expression.
     */
    java.util.List<java.lang.String>
        getExpressionList();
    /**
     * <code>repeated string expression = 1;</code>
     * @return The count of expression.
     */
    int getExpressionCount();
    /**
     * <code>repeated string expression = 1;</code>
     * @param index The index of the element to return.
     * @return The expression at the given index.
     */
    java.lang.String getExpression(int index);
    /**
     * <code>repeated string expression = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the expression at the given index.
     */
    com.google.protobuf.ByteString
        getExpressionBytes(int index);
  }
  /**
   * Protobuf type {@code IndProgramming2024Package.IndProgramming2024Project.Expressions}
   */
  public static final class Expressions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IndProgramming2024Package.IndProgramming2024Project.Expressions)
      ExpressionsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Expressions.class.getName());
    }
    // Use Expressions.newBuilder() to construct.
    private Expressions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Expressions() {
      expression_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.class, IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.Builder.class);
    }

    public static final int EXPRESSION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList expression_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string expression = 1;</code>
     * @return A list containing the expression.
     */
    public com.google.protobuf.ProtocolStringList
        getExpressionList() {
      return expression_;
    }
    /**
     * <code>repeated string expression = 1;</code>
     * @return The count of expression.
     */
    public int getExpressionCount() {
      return expression_.size();
    }
    /**
     * <code>repeated string expression = 1;</code>
     * @param index The index of the element to return.
     * @return The expression at the given index.
     */
    public java.lang.String getExpression(int index) {
      return expression_.get(index);
    }
    /**
     * <code>repeated string expression = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the expression at the given index.
     */
    public com.google.protobuf.ByteString
        getExpressionBytes(int index) {
      return expression_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < expression_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, expression_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < expression_.size(); i++) {
          dataSize += computeStringSizeNoTag(expression_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getExpressionList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions)) {
        return super.equals(obj);
      }
      IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions other = (IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions) obj;

      if (!getExpressionList()
          .equals(other.getExpressionList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getExpressionCount() > 0) {
        hash = (37 * hash) + EXPRESSION_FIELD_NUMBER;
        hash = (53 * hash) + getExpressionList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IndProgramming2024Package.IndProgramming2024Project.Expressions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IndProgramming2024Package.IndProgramming2024Project.Expressions)
        IndProgramming2024Package.IndProgramming2024Project.Hehe.ExpressionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.class, IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.Builder.class);
      }

      // Construct using IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        expression_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_descriptor;
      }

      @java.lang.Override
      public IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions getDefaultInstanceForType() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.getDefaultInstance();
      }

      @java.lang.Override
      public IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions build() {
        IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions buildPartial() {
        IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions result = new IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          expression_.makeImmutable();
          result.expression_ = expression_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions) {
          return mergeFrom((IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions other) {
        if (other == IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions.getDefaultInstance()) return this;
        if (!other.expression_.isEmpty()) {
          if (expression_.isEmpty()) {
            expression_ = other.expression_;
            bitField0_ |= 0x00000001;
          } else {
            ensureExpressionIsMutable();
            expression_.addAll(other.expression_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureExpressionIsMutable();
                expression_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList expression_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureExpressionIsMutable() {
        if (!expression_.isModifiable()) {
          expression_ = new com.google.protobuf.LazyStringArrayList(expression_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @return A list containing the expression.
       */
      public com.google.protobuf.ProtocolStringList
          getExpressionList() {
        expression_.makeImmutable();
        return expression_;
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @return The count of expression.
       */
      public int getExpressionCount() {
        return expression_.size();
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @param index The index of the element to return.
       * @return The expression at the given index.
       */
      public java.lang.String getExpression(int index) {
        return expression_.get(index);
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the expression at the given index.
       */
      public com.google.protobuf.ByteString
          getExpressionBytes(int index) {
        return expression_.getByteString(index);
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @param index The index to set the value at.
       * @param value The expression to set.
       * @return This builder for chaining.
       */
      public Builder setExpression(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureExpressionIsMutable();
        expression_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @param value The expression to add.
       * @return This builder for chaining.
       */
      public Builder addExpression(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureExpressionIsMutable();
        expression_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @param values The expression to add.
       * @return This builder for chaining.
       */
      public Builder addAllExpression(
          java.lang.Iterable<java.lang.String> values) {
        ensureExpressionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, expression_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpression() {
        expression_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string expression = 1;</code>
       * @param value The bytes of the expression to add.
       * @return This builder for chaining.
       */
      public Builder addExpressionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureExpressionIsMutable();
        expression_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IndProgramming2024Package.IndProgramming2024Project.Expressions)
    }

    // @@protoc_insertion_point(class_scope:IndProgramming2024Package.IndProgramming2024Project.Expressions)
    private static final IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions();
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Expressions>
        PARSER = new com.google.protobuf.AbstractParser<Expressions>() {
      @java.lang.Override
      public Expressions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Expressions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Expressions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public IndProgramming2024Package.IndProgramming2024Project.Hehe.Expressions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VarsAndValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IndProgramming2024Package.IndProgramming2024Project.VarsAndValues)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    int getVarsAndValuesCount();
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    boolean containsVarsAndValues(
        java.lang.String key);
    /**
     * Use {@link #getVarsAndValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Double>
    getVarsAndValues();
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Double>
    getVarsAndValuesMap();
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    double getVarsAndValuesOrDefault(
        java.lang.String key,
        double defaultValue);
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    double getVarsAndValuesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code IndProgramming2024Package.IndProgramming2024Project.VarsAndValues}
   */
  public static final class VarsAndValues extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IndProgramming2024Package.IndProgramming2024Project.VarsAndValues)
      VarsAndValuesOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        VarsAndValues.class.getName());
    }
    // Use VarsAndValues.newBuilder() to construct.
    private VarsAndValues(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VarsAndValues() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetVarsAndValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.class, IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.Builder.class);
    }

    public static final int VARS_AND_VALUES_FIELD_NUMBER = 1;
    private static final class VarsAndValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Double>newDefaultInstance(
                  IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_VarsAndValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> varsAndValues_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
    internalGetVarsAndValues() {
      if (varsAndValues_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VarsAndValuesDefaultEntryHolder.defaultEntry);
      }
      return varsAndValues_;
    }
    public int getVarsAndValuesCount() {
      return internalGetVarsAndValues().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    @java.lang.Override
    public boolean containsVarsAndValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetVarsAndValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVarsAndValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getVarsAndValues() {
      return getVarsAndValuesMap();
    }
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Double> getVarsAndValuesMap() {
      return internalGetVarsAndValues().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    @java.lang.Override
    public double getVarsAndValuesOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetVarsAndValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
     */
    @java.lang.Override
    public double getVarsAndValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetVarsAndValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetVarsAndValues(),
          VarsAndValuesDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
           : internalGetVarsAndValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
        varsAndValues__ = VarsAndValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, varsAndValues__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues)) {
        return super.equals(obj);
      }
      IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues other = (IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues) obj;

      if (!internalGetVarsAndValues().equals(
          other.internalGetVarsAndValues())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetVarsAndValues().getMap().isEmpty()) {
        hash = (37 * hash) + VARS_AND_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetVarsAndValues().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IndProgramming2024Package.IndProgramming2024Project.VarsAndValues}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IndProgramming2024Package.IndProgramming2024Project.VarsAndValues)
        IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetVarsAndValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableVarsAndValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.class, IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.Builder.class);
      }

      // Construct using IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableVarsAndValues().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor;
      }

      @java.lang.Override
      public IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues getDefaultInstanceForType() {
        return IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.getDefaultInstance();
      }

      @java.lang.Override
      public IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues build() {
        IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues buildPartial() {
        IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues result = new IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.varsAndValues_ = internalGetVarsAndValues();
          result.varsAndValues_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues) {
          return mergeFrom((IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues other) {
        if (other == IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues.getDefaultInstance()) return this;
        internalGetMutableVarsAndValues().mergeFrom(
            other.internalGetVarsAndValues());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
                varsAndValues__ = input.readMessage(
                    VarsAndValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableVarsAndValues().getMutableMap().put(
                    varsAndValues__.getKey(), varsAndValues__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Double> varsAndValues_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
          internalGetVarsAndValues() {
        if (varsAndValues_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              VarsAndValuesDefaultEntryHolder.defaultEntry);
        }
        return varsAndValues_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
          internalGetMutableVarsAndValues() {
        if (varsAndValues_ == null) {
          varsAndValues_ = com.google.protobuf.MapField.newMapField(
              VarsAndValuesDefaultEntryHolder.defaultEntry);
        }
        if (!varsAndValues_.isMutable()) {
          varsAndValues_ = varsAndValues_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return varsAndValues_;
      }
      public int getVarsAndValuesCount() {
        return internalGetVarsAndValues().getMap().size();
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      @java.lang.Override
      public boolean containsVarsAndValues(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetVarsAndValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getVarsAndValuesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double> getVarsAndValues() {
        return getVarsAndValuesMap();
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.Double> getVarsAndValuesMap() {
        return internalGetVarsAndValues().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      @java.lang.Override
      public double getVarsAndValuesOrDefault(
          java.lang.String key,
          double defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetVarsAndValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      @java.lang.Override
      public double getVarsAndValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetVarsAndValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearVarsAndValues() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableVarsAndValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      public Builder removeVarsAndValues(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableVarsAndValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double>
          getMutableVarsAndValues() {
        bitField0_ |= 0x00000001;
        return internalGetMutableVarsAndValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      public Builder putVarsAndValues(
          java.lang.String key,
          double value) {
        if (key == null) { throw new NullPointerException("map key"); }

        internalGetMutableVarsAndValues().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; vars_and_values = 1;</code>
       */
      public Builder putAllVarsAndValues(
          java.util.Map<java.lang.String, java.lang.Double> values) {
        internalGetMutableVarsAndValues().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IndProgramming2024Package.IndProgramming2024Project.VarsAndValues)
    }

    // @@protoc_insertion_point(class_scope:IndProgramming2024Package.IndProgramming2024Project.VarsAndValues)
    private static final IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues();
    }

    public static IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VarsAndValues>
        PARSER = new com.google.protobuf.AbstractParser<VarsAndValues>() {
      @java.lang.Override
      public VarsAndValues parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VarsAndValues> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VarsAndValues> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public IndProgramming2024Package.IndProgramming2024Project.Hehe.VarsAndValues getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_VarsAndValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_VarsAndValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhehe.proto\0223IndProgramming2024Package." +
      "IndProgramming2024Project\"!\n\013Expressions" +
      "\022\022\n\nexpression\030\001 \003(\t\"\265\001\n\rVarsAndValues\022n" +
      "\n\017vars_and_values\030\001 \003(\0132U.IndProgramming" +
      "2024Package.IndProgramming2024Project.Va" +
      "rsAndValues.VarsAndValuesEntry\0324\n\022VarsAn" +
      "dValuesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\001" +
      ":\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IndProgramming2024Package_IndProgramming2024Project_Expressions_descriptor,
        new java.lang.String[] { "Expression", });
    internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor,
        new java.lang.String[] { "VarsAndValues", });
    internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_VarsAndValuesEntry_descriptor =
      internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_descriptor.getNestedTypes().get(0);
    internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_VarsAndValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IndProgramming2024Package_IndProgramming2024Project_VarsAndValues_VarsAndValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
